services:
  - type: web
    name: ibkr-broker-simulator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: ibkr-broker-simulator
          property: port
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
    healthCheckPath: /health